In [2]:
import pandas as pd

jet = pd.read_table('train_data.txt',sep=' ',header=None)

jet.head()
jet.drop([26,27],axis=1,inplace=True)

jet_index_1 = jet.iloc[:,0].tolist()
jet_index_2 = jet.iloc[:,1].tolist()

jet_index = pd.MultiIndex.from_arrays([jet_index_1,jet_index_2],names=['id','flight'])

jet.set_index(jet_index,inplace=True)
jet.drop([0,1],axis=1,inplace=True)
jet

                 2       3      4       5       6        7        8      9   \
id  flight
1   1       34.9983  0.8400  100.0  449.44  555.32  1358.61  1137.23   5.48
    2       41.9982  0.8408  100.0  445.00  549.90  1353.22  1125.78   3.91
    3       24.9988  0.6218   60.0  462.54  537.31  1256.76  1047.45   7.05
    4       42.0077  0.8416  100.0  445.00  549.51  1354.03  1126.38   3.91
    5       25.0005  0.6203   60.0  462.54  537.07  1257.71  1047.93   7.05
...             ...     ...    ...     ...     ...      ...      ...    ...
260 312     20.0037  0.7000  100.0  491.19  608.79  1495.60  1269.51   9.35
    313     10.0022  0.2510  100.0  489.05  605.81  1514.32  1324.12  10.52
    314     25.0041  0.6200   60.0  462.54  537.48  1276.24  1057.92   7.05
    315     25.0033  0.6220   60.0  462.54  537.84  1272.95  1066.30   7.05
    316     35.0036  0.8400  100.0  449.44  556.64  1374.61  1145.52   5.48

               10      11  ...      16       17       18       19    20   21  \
id  flight                 ...
1   1        8.00  194.64  ...  183.06  2387.72  8048.56   9.3461  0.02  334
    2        5.71  138.51  ...  130.42  2387.66  8072.30   9.3774  0.02  330
    3        9.02  175.71  ...  164.22  2028.03  7864.87  10.8941  0.02  309
    4        5.71  138.46  ...  130.72  2387.61  8068.66   9.3528  0.02  329
    5        9.03  175.05  ...  164.31  2028.00  7861.23  10.8963  0.02  309
...           ...     ...  ...     ...      ...      ...      ...   ...  ...
260 312     13.66  334.00  ...  314.05  2389.02  8169.64   9.3035  0.03  369
    313     15.50  392.46  ...  371.22  2388.42  8245.36   8.7586  0.03  374
    314      9.04  175.11  ...  163.74  2030.33  7971.25  11.0657  0.02  310
    315      9.04  174.81  ...  164.37  2030.35  7972.47  11.0537  0.02  311
    316      8.01  194.33  ...  183.09  2390.38  8185.35   9.3998  0.02  338

              22      23     24       25
id  flight
1   1       2223  100.00  14.73   8.8071
    2       2212  100.00  10.41   6.2665
    3       1915   84.93  14.08   8.6723
    4       2212  100.00  10.59   6.4701
    5       1915   84.93  14.13   8.5286
...          ...     ...    ...      ...
260 312     2324  100.00  24.36  14.5189
    313     2319  100.00  28.10  16.9454
    314     1915   84.93  14.19   8.5503
    315     1915   84.93  14.05   8.3729
    316     2223  100.00  14.75   8.8446

[53759 rows x 24 columns]

In [3]:
jet.describe

<bound method NDFrame.describe of                  2       3      4       5       6        7        8      9   \
id  flight
1   1       34.9983  0.8400  100.0  449.44  555.32  1358.61  1137.23   5.48
    2       41.9982  0.8408  100.0  445.00  549.90  1353.22  1125.78   3.91
    3       24.9988  0.6218   60.0  462.54  537.31  1256.76  1047.45   7.05
    4       42.0077  0.8416  100.0  445.00  549.51  1354.03  1126.38   3.91
    5       25.0005  0.6203   60.0  462.54  537.07  1257.71  1047.93   7.05
...             ...     ...    ...     ...     ...      ...      ...    ...
260 312     20.0037  0.7000  100.0  491.19  608.79  1495.60  1269.51   9.35
    313     10.0022  0.2510  100.0  489.05  605.81  1514.32  1324.12  10.52
    314     25.0041  0.6200   60.0  462.54  537.48  1276.24  1057.92   7.05
    315     25.0033  0.6220   60.0  462.54  537.84  1272.95  1066.30   7.05
    316     35.0036  0.8400  100.0  449.44  556.64  1374.61  1145.52   5.48

               10      11  ...      16       17       18       19    20   21  \
id  flight                 ...
1   1        8.00  194.64  ...  183.06  2387.72  8048.56   9.3461  0.02  334
    2        5.71  138.51  ...  130.42  2387.66  8072.30   9.3774  0.02  330
    3        9.02  175.71  ...  164.22  2028.03  7864.87  10.8941  0.02  309
    4        5.71  138.46  ...  130.72  2387.61  8068.66   9.3528  0.02  329
    5        9.03  175.05  ...  164.31  2028.00  7861.23  10.8963  0.02  309
...           ...     ...  ...     ...      ...      ...      ...   ...  ...
260 312     13.66  334.00  ...  314.05  2389.02  8169.64   9.3035  0.03  369
    313     15.50  392.46  ...  371.22  2388.42  8245.36   8.7586  0.03  374
    314      9.04  175.11  ...  163.74  2030.33  7971.25  11.0657  0.02  310
    315      9.04  174.81  ...  164.37  2030.35  7972.47  11.0537  0.02  311
    316      8.01  194.33  ...  183.09  2390.38  8185.35   9.3998  0.02  338

              22      23     24       25
id  flight
1   1       2223  100.00  14.73   8.8071
    2       2212  100.00  10.41   6.2665
    3       1915   84.93  14.08   8.6723
    4       2212  100.00  10.59   6.4701
    5       1915   84.93  14.13   8.5286
...          ...     ...    ...      ...
260 312     2324  100.00  24.36  14.5189
    313     2319  100.00  28.10  16.9454
    314     1915   84.93  14.19   8.5503
    315     1915   84.93  14.05   8.3729
    316     2223  100.00  14.75   8.8446

[53759 rows x 24 columns]>